### ISSUE TITLE
Finding a way to do spatialite to XML conversion in Java

### ISSUE THREAD

**Issue by jafshin** [agentsoz/matsim-melbourne#5]
Here I've attached a small CBD only network in SQLite format - the output of the network generation process. Writing it into an XML file in R takes a couple of hours while the rest of the process happens in less than 5 min for Greater Melbourne. Would be great if we can find a way to do the conversion in Java and directly feed into MATSim as an input instead.

[MATSimNetwork_test_22July_croped.zip](https://github.com/agentsoz/matsim-melbourne/files/4951701/MATSimNetwork_test_22July_croped.zip)

**Comment by alanboth** [comment]
Agreed! We would need to update our sqlite output to include the GTFS parts though. We would need the vehicleTypes and vehicles tables to make transitVehicles as well as the transitStops, routeProfile, and departures tables to make transitSchedule.
